!obj:pylearn2.train.Train {
    dataset: &train !pkl: "%(data_dir)s/%(dataset_prefix)s_train.pkl",
    model: !obj:pylearn2.models.mlp.MLP {
        batch_size: 100,
        layers: [
                 !obj:pylearn2.models.mlp.CompositeLayer {
                     layer_name: "h0",
                     inputs_to_layers: {
                          0: [0],
                          1: [1],
                          2: [2],
                          3: [3]
                     },
                     layers: [
                              !obj:pylearn2.models.mlp.RectifiedLinear {
                                   layer_name: 'time0',
                                   dim: 20,
                                   sparse_init: 15
                               }, !obj:pylearn2.models.mlp.RectifiedLinear {
                                   layer_name: 'temp0',
                                   dim: 20,
                                   sparse_init: 15
                               }, !obj:pylearn2.models.mlp.RectifiedLinear {
                                   layer_name: 'day_of_week0',
                                   dim: 20,
                                   sparse_init: 15
                               }
                      ],
            }, !obj:pylearn2.models.mlp.Softmax {
                max_col_norm: 1.9365,
                layer_name: 'y',
                n_classes: 10,
                istdev: .05
            }
        ],
        input_space: !obj:pylearn2.space.CompositeSpace {
            components: [
                         !obj:pylearn2.space.Conv2DSpace {
                             shape: [10,1],
                             num_channels: 1
                         }, !obj:pylearn2.space.VectorSpace {
                             dim: 1,
                         }, !obj:pylearn2.space.VectorSpace {
                             dim: 1,
                         }, !obj:pylearn2.space.VectorSpace {
                             dim: 7,
                             sparse: True
                         }
            ]
        },
    },
    algorithm: !obj:pylearn2.training_algorithms.bgd.BGD {
        batch_size: 100,
        line_search_mode: 'exhaustive',
        conjugate: 1,
        monitoring_dataset:
        {
            'train' : *train,
            'valid' : !pkl: "%(data_dir)s/%(dataset_prefix)s_valid.pkl",
            'test'  : !pkl: "%(data_dir)s/%(dataset_prefix)s_test.pkl",
        },
        termination_criterion: !obj:pylearn2.termination_criteria.MonitorBased {
            channel_name: "valid_y_misclass"
        }
    },
    extensions: [
        !obj:pylearn2.train_extensions.best_params.MonitorBasedSaveBest {
             channel_name: 'valid_y_misclass',
             save_path: "models/%(saved_model_prefix)s_best.pkl"
        },
    ],
    save_path: "models/%(saved_model_prefix)s.pkl",
    save_freq: 1
}
