!obj:pylearn2.train.Train {
    dataset: &train !pkl: "%(data_dir)s/%(dataset_prefix)s_train.pkl",
    model: !obj:pylearn2.models.mlp.MLP {
        batch_size: 100,
        input_space: !obj:pylearn2.space.Conv2DSpace {
            shape: [672,1],
            num_channels: 1
        },
        layers: [ !obj:pylearn2.models.mlp.ConvRectifiedLinear {
                     layer_name: 'h0',
                     output_channels: 4,
                     irange: .05,
                     kernel_shape: [5, 1],
                     pool_shape: [2, 1],
                     pool_stride: [2, 1],
                     max_kernel_norm: 1.9365
                 }, !obj:pylearn2.models.mlp.ConvRectifiedLinear {
                     layer_name: 'h1',
                     output_channels: 4,
                     irange: .05,
                     kernel_shape: [5, 1],
                     pool_shape: [2, 1],
                     pool_stride: [2, 1],
                     max_kernel_norm: 1.9365
                 }, !obj:pylearn2.models.mlp.RectifiedLinear {
                     layer_name: 'h2',
                     dim: 4,
                     sparse_init: 15
                 }, !obj:pylearn2.models.mlp.Softmax {
                     max_col_norm: 1.9365,
                     layer_name: 'y',
                     n_classes: 2,
                     istdev: .05
                 }
                ],
    },
    algorithm: !obj:pylearn2.training_algorithms.bgd.BGD {
        batch_size: 100,
        line_search_mode: 'exhaustive',
        conjugate: 1,
        monitoring_dataset:
        {
            'train' : *train,
            'valid' : !pkl: "%(data_dir)s/%(dataset_prefix)s_valid.pkl",
            'test'  : !pkl: "%(data_dir)s/%(dataset_prefix)s_test.pkl",
        },
        termination_criterion: !obj:pylearn2.termination_criteria.MonitorBased {
            channel_name: "valid_y_misclass"
        }
    },
    extensions: [
        !obj:pylearn2.train_extensions.best_params.MonitorBasedSaveBest {
             channel_name: 'valid_y_misclass',
             save_path: "models/%(saved_model_prefix)s_best.pkl"
        },
    ],
    save_path: "models/%(saved_model_prefix)s.pkl",
    save_freq: 1
}
